### PR TITLE
Changed core version (pom.xml) and version message to 0.3.1

### PR DESCRIPTION
**Pull request by brenzosa**
Other minor improvements made were needed by the mobile wallet

### CODE REVIEW

**Comment by MitchellCash** [comment]
What's happening with commit ebd6026.

It looks like you would rather be fetching from upstream and merging over master instead of what's happening in that commit?

I few similar looking commits as well that could probably be squashed (1416b08 and af04bcf)?

**Comment by brenzosa** [comment]
ebd6026 seems to be for the changes I pulled from PaycoinFoundation so it was for bringing my repository up-to-date with this one (https://github.com/brenzosa/paycoinj/commit/ebd602616e161c3bc564fb6dd39a08fdea9ab222).

The actual changes in this pull request can be seen here (1416b08 and af04bcf seem to be included correctly):  https://github.com/PaycoinFoundation/paycoinj/pull/16/files

**Comment by MitchellCash** [comment]
I think I should teach you some git tricks for cleaner commits and pulls. For example you shouldn't pull the changes from paycoinfoundation like you did but rather doing a clean merge etc. I can chat on slack. We should clean this up before merging

**Comment by MitchellCash** [comment]
@brenzosa we should be splitting these up into their own pull requests and this still needs a bit of a clean up. I might do it to at least get the protocol change in the wallet.

**Comment by MitchellCash** [comment]
@brenzosa can you please review the pull request splits I've made above (I just cherry-picked your commits so you'll still get the credit).

Let me know if any need merging etc.

If everything is okay please close this.

**Comment by brenzosa** [comment]
Sure go ahead, that's really the only important change so it should be easy to add.  I'll re-open another PR for the other stuff, thanks

**Pull request closed without merging**
